source 'https://rubygems.org'

gem 'multi_xml'
gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'foundation-rails'
gem 'omniauth'
gem 'goodreads'
gem 'omniauth-oauth'
gem 'pry'
gem 'figaro'
gem 'faraday'
gem 'sucker_punch', '~> 1.0'

group :development, :test do
  gem 'simplecov'
  gem 'vcr'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'byebug'
  gem 'rspec-rails'
  gem 'web-console', '~> 2.0'
  gem 'capybara'
  gem 'spring'
end
