# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7acdd615988f45dbf7afd180aca4b60241945e73e2aa26b694f3e05084698555d57e6422642f89ef7874f8abea0928aa86bec63f27d419bfbaa993025697d137

test:
  secret_key_base: 26bd6f5f8a8b26d91e49ea0753b1c1f7841c1eae12cb312f9f72d3b6d3fc06241f8852dd7b42a0b219dd096acabdf55e83fb0422cb29b30d2c36c4c2bd677591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
